name: Gradle RC Watchdog

on:
  schedule:
    - cron:  '0 0 14 * *'

jobs:
  check:
    name: Verify the Latest Gradle Version
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: gradle/gradle-command-action@v2.3.3
      with:
        arguments: check --stacktrace
        gradle-version: rc
